fix: support .pkg extraction for macOS Hugo releases

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -8,18 +8,34 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=../lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
+platform="$(get_platform)"
+
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 # TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+if [ "$platform" = "darwin" ]; then
+  release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.pkg"
+else
+  release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+fi
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+# Extract contents of file into the download directory
+if [ "$platform" = "darwin" ]; then
+  # Extract .pkg
+  pkgutil --expand "$release_file" "$ASDF_DOWNLOAD_PATH/pkg_expand"
+  cd "$ASDF_DOWNLOAD_PATH/pkg_expand"
+  cpio -i < Payload
+  mv hugo "$ASDF_DOWNLOAD_PATH/"
+  cd -
+  rm -rf "$ASDF_DOWNLOAD_PATH/pkg_expand"
+else
+  tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+fi
 
 chmod +x "$ASDF_DOWNLOAD_PATH/$TOOL_NAME"
 
-# Remove the tar.gz file since we don't need to keep it
+# Remove the file since we don't need to keep it
 rm "$release_file"
